name: "Build"

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                shell: bash

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Versions
              run: npm version; aws --version
              
            - name: Test
              run: |
                FILES=$(git log -m -1 --name-only --pretty="format:")
                if [ $(echo $FILES | grep -c "github") -eq  0 ]; then
                    echo "No changes on github"
                else
                    echo "We got changes"
                fi
