name: "Build"

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                shell: bash

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Versions
              run: npm version; aws --version
              
            - name: Test
              env:
                SUPER_SECRET: ${{ secrets.TEST }} 
              run: |
                echo "this is just testing the i-secret ..."
                echo "$SUPER_SECRET"
                git log -n 1 --name-only --pretty="format:"
                FILES=$(git log -m -1 --name-only --pretty="format:" | grep "github")
                if [ $(echo $FILES | grep -c "github") -eq  0 ]; then
                    echo "No changes on github"
                else
                    echo "We got changes"
                fi
